2016-08-25 00:00:19,651 INFO org.apache.hadoop.mapred.JobTracker: attempt_201608242349_0001_m_000039_0 is 596892 ms debug.
2016-08-25 00:03:39,650 INFO org.apache.hadoop.mapred.JobTracker: Lost tracker 'tracker_slave1:127.0.0.1/127.0.0.1:43647'
2016-08-25 00:03:39,651 INFO org.apache.hadoop.mapred.TaskInProgress: Error from attempt_201608242349_0001_m_000039_0 on tracker_slave1:127.0.0.1/127.0.0.1:43647: Lost task tracker: tracker_slave1:127.0.0.1/127.0.0.1:43647
2016-08-25 00:03:39,656 INFO org.apache.hadoop.mapred.JobTracker: Removing task 'attempt_201608242349_0001_m_000039_0'
2016-08-25 00:03:39,656 INFO org.apache.hadoop.mapred.JobTracker: attempt_201608242349_0001_m_000039_0 is 796893 ms debug.
2016-08-25 00:03:39,656 INFO org.apache.hadoop.mapred.JobTracker: Launching task attempt_201608242349_0001_m_000039_0 timed out.
2016-08-25 00:03:41,264 INFO org.apache.hadoop.mapred.JobTracker: Adding task (JOB_SETUP) 'attempt_201608242349_0001_m_000039_1' to tip task_201608242349_0001_m_000039, for tracker 'tracker_slave3:localhost/127.0.0.1:42917'
2016-08-25 00:03:44,302 INFO org.apache.hadoop.mapred.TaskInProgress: Error from attempt_201608242349_0001_m_000039_1 on tracker_slave3:localhost/127.0.0.1:42917: java.lang.Throwable: Child Error
	at org.apache.hadoop.mapred.TaskRunner.run(TaskRunner.java:249)
Caused by: java.io.FileNotFoundException: File does not exist: /user/hduser/terasort-output10-block-256/_partition.lst
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:624)
	at org.apache.hadoop.mapreduce.filecache.TaskDistributedCacheManager.setup(TaskDistributedCacheManager.java:166)
	at org.apache.hadoop.mapred.TaskRunner$1.run(TaskRunner.java:187)
	at org.apache.hadoop.mapred.TaskRunner$1.run(TaskRunner.java:182)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:742)
	at org.apache.hadoop.mapred.TaskRunner.run(TaskRunner.java:182)

2016-08-25 00:03:47,307 INFO org.apache.hadoop.mapred.JobTracker: Adding task (JOB_SETUP) 'attempt_201608242349_0001_r_000002_0' to tip task_201608242349_0001_r_000002, for tracker 'tracker_slave3:localhost/127.0.0.1:42917'
2016-08-25 00:03:47,308 INFO org.apache.hadoop.mapred.JobTracker: Removing task 'attempt_201608242349_0001_m_000039_1'
2016-08-25 00:03:50,316 INFO org.apache.hadoop.mapred.TaskInProgress: Error from attempt_201608242349_0001_r_000002_0 on tracker_slave3:localhost/127.0.0.1:42917: java.lang.Throwable: Child Error
	at org.apache.hadoop.mapred.TaskRunner.run(TaskRunner.java:249)
Caused by: java.io.FileNotFoundException: File does not exist: /user/hduser/terasort-output10-block-256/_partition.lst
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:624)
	at org.apache.hadoop.mapreduce.filecache.TaskDistributedCacheManager.setup(TaskDistributedCacheManager.java:166)
	at org.apache.hadoop.mapred.TaskRunner$1.run(TaskRunner.java:187)
	at org.apache.hadoop.mapred.TaskRunner$1.run(TaskRunner.java:182)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:742)
	at org.apache.hadoop.mapred.TaskRunner.run(TaskRunner.java:182)

2016-08-25 00:03:53,322 INFO org.apache.hadoop.mapred.JobTracker: Removing task 'attempt_201608242349_0001_r_000002_0'
2016-08-25 00:03:53,335 INFO org.apache.hadoop.mapred.JobTracker: Adding task (JOB_SETUP) 'attempt_201608242349_0001_m_000039_2' to tip task_201608242349_0001_m_000039, for tracker 'tracker_slave2:127.0.0.1/127.0.0.1:37601'
2016-08-25 00:03:56,398 INFO org.apache.hadoop.mapred.TaskInProgress: Error from attempt_201608242349_0001_m_000039_2 on tracker_slave2:127.0.0.1/127.0.0.1:37601: java.lang.Throwable: Child Error
	at org.apache.hadoop.mapred.TaskRunner.run(TaskRunner.java:249)
Caused by: java.io.FileNotFoundException: File does not exist: /user/hduser/terasort-output10-block-256/_partition.lst
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:624)
	at org.apache.hadoop.mapreduce.filecache.TaskDistributedCacheManager.setup(TaskDistributedCacheManager.java:166)
	at org.apache.hadoop.mapred.TaskRunner$1.run(TaskRunner.java:187)
	at org.apache.hadoop.mapred.TaskRunner$1.run(TaskRunner.java:182)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:742)
	at org.apache.hadoop.mapred.TaskRunner.run(TaskRunner.java:182)

2016-08-25 00:03:59,403 INFO org.apache.hadoop.mapred.JobTracker: Adding task (JOB_SETUP) 'attempt_201608242349_0001_r_000002_1' to tip task_201608242349_0001_r_000002, for tracker 'tracker_slave2:127.0.0.1/127.0.0.1:37601'
2016-08-25 00:03:59,403 INFO org.apache.hadoop.mapred.JobTracker: Removing task 'attempt_201608242349_0001_m_000039_2'
2016-08-25 00:04:02,411 INFO org.apache.hadoop.mapred.TaskInProgress: Error from attempt_201608242349_0001_r_000002_1 on tracker_slave2:127.0.0.1/127.0.0.1:37601: java.lang.Throwable: Child Error
	at org.apache.hadoop.mapred.TaskRunner.run(TaskRunner.java:249)
Caused by: java.io.FileNotFoundException: File does not exist: /user/hduser/terasort-output10-block-256/_partition.lst
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:624)
	at org.apache.hadoop.mapreduce.filecache.TaskDistributedCacheManager.setup(TaskDistributedCacheManager.java:166)
	at org.apache.hadoop.mapred.TaskRunner$1.run(TaskRunner.java:187)
	at org.apache.hadoop.mapred.TaskRunner$1.run(TaskRunner.java:182)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:742)
	at org.apache.hadoop.mapred.TaskRunner.run(TaskRunner.java:182)

2016-08-25 00:04:05,417 INFO org.apache.hadoop.mapred.JobTracker: Removing task 'attempt_201608242349_0001_r_000002_1'
2016-08-25 00:04:05,504 INFO org.apache.hadoop.mapred.JobTracker: Adding task (JOB_SETUP) 'attempt_201608242349_0001_m_000039_3' to tip task_201608242349_0001_m_000039, for tracker 'tracker_slave5:127.0.0.1/127.0.0.1:41055'
2016-08-25 00:04:08,561 INFO org.apache.hadoop.mapred.TaskInProgress: Error from attempt_201608242349_0001_m_000039_3 on tracker_slave5:127.0.0.1/127.0.0.1:41055: java.lang.Throwable: Child Error
	at org.apache.hadoop.mapred.TaskRunner.run(TaskRunner.java:249)
Caused by: java.io.FileNotFoundException: File does not exist: /user/hduser/terasort-output10-block-256/_partition.lst
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:624)
	at org.apache.hadoop.mapreduce.filecache.TaskDistributedCacheManager.setup(TaskDistributedCacheManager.java:166)
	at org.apache.hadoop.mapred.TaskRunner$1.run(TaskRunner.java:187)
	at org.apache.hadoop.mapred.TaskRunner$1.run(TaskRunner.java:182)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:742)
	at org.apache.hadoop.mapred.TaskRunner.run(TaskRunner.java:182)

2016-08-25 00:04:11,568 INFO org.apache.hadoop.mapred.JobTracker: Adding task (JOB_SETUP) 'attempt_201608242349_0001_r_000002_2' to tip task_201608242349_0001_r_000002, for tracker 'tracker_slave5:127.0.0.1/127.0.0.1:41055'
2016-08-25 00:04:11,568 INFO org.apache.hadoop.mapred.JobTracker: Removing task 'attempt_201608242349_0001_m_000039_3'
2016-08-25 00:04:14,577 INFO org.apache.hadoop.mapred.TaskInProgress: Error from attempt_201608242349_0001_r_000002_2 on tracker_slave5:127.0.0.1/127.0.0.1:41055: java.lang.Throwable: Child Error
	at org.apache.hadoop.mapred.TaskRunner.run(TaskRunner.java:249)
Caused by: java.io.FileNotFoundException: File does not exist: /user/hduser/terasort-output10-block-256/_partition.lst
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:624)
	at org.apache.hadoop.mapreduce.filecache.TaskDistributedCacheManager.setup(TaskDistributedCacheManager.java:166)
	at org.apache.hadoop.mapred.TaskRunner$1.run(TaskRunner.java:187)
	at org.apache.hadoop.mapred.TaskRunner$1.run(TaskRunner.java:182)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:742)
	at org.apache.hadoop.mapred.TaskRunner.run(TaskRunner.java:182)

2016-08-25 00:04:17,585 INFO org.apache.hadoop.mapred.JobTracker: Removing task 'attempt_201608242349_0001_r_000002_2'
2016-08-25 00:04:20,521 INFO org.apache.hadoop.mapred.JobTracker: Adding task (JOB_SETUP) 'attempt_201608242349_0001_m_000039_4' to tip task_201608242349_0001_m_000039, for tracker 'tracker_slave4:127.0.0.1/127.0.0.1:46320'
2016-08-25 00:04:23,564 INFO org.apache.hadoop.mapred.TaskInProgress: Error from attempt_201608242349_0001_m_000039_4 on tracker_slave4:127.0.0.1/127.0.0.1:46320: java.lang.Throwable: Child Error
	at org.apache.hadoop.mapred.TaskRunner.run(TaskRunner.java:249)
Caused by: java.io.FileNotFoundException: File does not exist: /user/hduser/terasort-output10-block-256/_partition.lst
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:624)
	at org.apache.hadoop.mapreduce.filecache.TaskDistributedCacheManager.setup(TaskDistributedCacheManager.java:166)
	at org.apache.hadoop.mapred.TaskRunner$1.run(TaskRunner.java:187)
	at org.apache.hadoop.mapred.TaskRunner$1.run(TaskRunner.java:182)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:742)
	at org.apache.hadoop.mapred.TaskRunner.run(TaskRunner.java:182)

2016-08-25 00:04:26,567 INFO org.apache.hadoop.mapred.TaskInProgress: TaskInProgress task_201608242349_0001_m_000039 has failed 4 times.
2016-08-25 00:04:26,568 INFO org.apache.hadoop.mapred.JobInProgress: Aborting job job_201608242349_0001
2016-08-25 00:04:26,570 INFO org.apache.hadoop.mapred.JobInProgress: Killing job 'job_201608242349_0001'
2016-08-25 00:04:26,570 INFO org.apache.hadoop.mapred.JobTracker: Adding task (JOB_CLEANUP) 'attempt_201608242349_0001_m_000038_0' to tip task_201608242349_0001_m_000038, for tracker 'tracker_slave4:127.0.0.1/127.0.0.1:46320'
2016-08-25 00:04:26,570 INFO org.apache.hadoop.mapred.JobTracker: Removing task 'attempt_201608242349_0001_m_000039_4'
2016-08-25 00:04:29,574 INFO org.apache.hadoop.mapred.TaskInProgress: Error from attempt_201608242349_0001_m_000038_0 on tracker_slave4:127.0.0.1/127.0.0.1:46320: java.lang.Throwable: Child Error
	at org.apache.hadoop.mapred.TaskRunner.run(TaskRunner.java:249)
Caused by: java.io.FileNotFoundException: File does not exist: /user/hduser/terasort-output10-block-256/_partition.lst
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:624)
	at org.apache.hadoop.mapreduce.filecache.TaskDistributedCacheManager.setup(TaskDistributedCacheManager.java:166)
	at org.apache.hadoop.mapred.TaskRunner$1.run(TaskRunner.java:187)
	at org.apache.hadoop.mapred.TaskRunner$1.run(TaskRunner.java:182)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:742)
	at org.apache.hadoop.mapred.TaskRunner.run(TaskRunner.java:182)

2016-08-25 00:04:32,578 INFO org.apache.hadoop.mapred.JobTracker: Adding task (JOB_CLEANUP) 'attempt_201608242349_0001_r_000001_0' to tip task_201608242349_0001_r_000001, for tracker 'tracker_slave4:127.0.0.1/127.0.0.1:46320'
2016-08-25 00:04:32,579 INFO org.apache.hadoop.mapred.JobTracker: Removing task 'attempt_201608242349_0001_m_000038_0'
2016-08-25 00:04:35,587 INFO org.apache.hadoop.mapred.TaskInProgress: Error from attempt_201608242349_0001_r_000001_0 on tracker_slave4:127.0.0.1/127.0.0.1:46320: java.lang.Throwable: Child Error
	at org.apache.hadoop.mapred.TaskRunner.run(TaskRunner.java:249)
Caused by: java.io.FileNotFoundException: File does not exist: /user/hduser/terasort-output10-block-256/_partition.lst
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:624)
	at org.apache.hadoop.mapreduce.filecache.TaskDistributedCacheManager.setup(TaskDistributedCacheManager.java:166)
	at org.apache.hadoop.mapred.TaskRunner$1.run(TaskRunner.java:187)
	at org.apache.hadoop.mapred.TaskRunner$1.run(TaskRunner.java:182)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:742)
	at org.apache.hadoop.mapred.TaskRunner.run(TaskRunner.java:182)

2016-08-25 00:04:38,591 INFO org.apache.hadoop.mapred.JobTracker: Removing task 'attempt_201608242349_0001_r_000001_0'
2016-08-25 00:04:38,603 INFO org.apache.hadoop.mapred.JobTracker: Adding task (JOB_CLEANUP) 'attempt_201608242349_0001_m_000038_1' to tip task_201608242349_0001_m_000038, for tracker 'tracker_slave5:127.0.0.1/127.0.0.1:41055'
2016-08-25 00:04:41,607 INFO org.apache.hadoop.mapred.TaskInProgress: Error from attempt_201608242349_0001_m_000038_1 on tracker_slave5:127.0.0.1/127.0.0.1:41055: java.lang.Throwable: Child Error
	at org.apache.hadoop.mapred.TaskRunner.run(TaskRunner.java:249)
Caused by: java.io.FileNotFoundException: File does not exist: /user/hduser/terasort-output10-block-256/_partition.lst
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:624)
	at org.apache.hadoop.mapreduce.filecache.TaskDistributedCacheManager.setup(TaskDistributedCacheManager.java:166)
	at org.apache.hadoop.mapred.TaskRunner$1.run(TaskRunner.java:187)
	at org.apache.hadoop.mapred.TaskRunner$1.run(TaskRunner.java:182)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:742)
	at org.apache.hadoop.mapred.TaskRunner.run(TaskRunner.java:182)

2016-08-25 00:04:44,612 INFO org.apache.hadoop.mapred.JobTracker: Adding task (JOB_CLEANUP) 'attempt_201608242349_0001_r_000001_1' to tip task_201608242349_0001_r_000001, for tracker 'tracker_slave5:127.0.0.1/127.0.0.1:41055'
2016-08-25 00:04:44,613 INFO org.apache.hadoop.mapred.JobTracker: Removing task 'attempt_201608242349_0001_m_000038_1'
2016-08-25 00:04:47,619 INFO org.apache.hadoop.mapred.TaskInProgress: Error from attempt_201608242349_0001_r_000001_1 on tracker_slave5:127.0.0.1/127.0.0.1:41055: java.lang.Throwable: Child Error
	at org.apache.hadoop.mapred.TaskRunner.run(TaskRunner.java:249)
Caused by: java.io.FileNotFoundException: File does not exist: /user/hduser/terasort-output10-block-256/_partition.lst
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:624)
	at org.apache.hadoop.mapreduce.filecache.TaskDistributedCacheManager.setup(TaskDistributedCacheManager.java:166)
	at org.apache.hadoop.mapred.TaskRunner$1.run(TaskRunner.java:187)
	at org.apache.hadoop.mapred.TaskRunner$1.run(TaskRunner.java:182)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:742)
	at org.apache.hadoop.mapred.TaskRunner.run(TaskRunner.java:182)

2016-08-25 00:04:50,626 INFO org.apache.hadoop.mapred.JobInProgress: TaskTracker at 'slave5' turned 'flaky'
2016-08-25 00:04:50,626 INFO org.apache.hadoop.mapred.JobTracker: Removing task 'attempt_201608242349_0001_r_000001_1'
2016-08-25 00:04:53,358 INFO org.apache.hadoop.mapred.JobTracker: Adding task (JOB_CLEANUP) 'attempt_201608242349_0001_m_000038_2' to tip task_201608242349_0001_m_000038, for tracker 'tracker_slave3:localhost/127.0.0.1:42917'
2016-08-25 00:04:56,360 INFO org.apache.hadoop.mapred.TaskInProgress: Error from attempt_201608242349_0001_m_000038_2 on tracker_slave3:localhost/127.0.0.1:42917: java.lang.Throwable: Child Error
	at org.apache.hadoop.mapred.TaskRunner.run(TaskRunner.java:249)
Caused by: java.io.FileNotFoundException: File does not exist: /user/hduser/terasort-output10-block-256/_partition.lst
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:624)
	at org.apache.hadoop.mapreduce.filecache.TaskDistributedCacheManager.setup(TaskDistributedCacheManager.java:166)
	at org.apache.hadoop.mapred.TaskRunner$1.run(TaskRunner.java:187)
	at org.apache.hadoop.mapred.TaskRunner$1.run(TaskRunner.java:182)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:742)
	at org.apache.hadoop.mapred.TaskRunner.run(TaskRunner.java:182)

2016-08-25 00:04:59,367 INFO org.apache.hadoop.mapred.JobTracker: Adding task (JOB_CLEANUP) 'attempt_201608242349_0001_r_000001_2' to tip task_201608242349_0001_r_000001, for tracker 'tracker_slave3:localhost/127.0.0.1:42917'
2016-08-25 00:04:59,368 INFO org.apache.hadoop.mapred.JobTracker: Removing task 'attempt_201608242349_0001_m_000038_2'
2016-08-25 00:05:02,371 INFO org.apache.hadoop.mapred.TaskInProgress: Error from attempt_201608242349_0001_r_000001_2 on tracker_slave3:localhost/127.0.0.1:42917: java.lang.Throwable: Child Error
	at org.apache.hadoop.mapred.TaskRunner.run(TaskRunner.java:249)
Caused by: java.io.FileNotFoundException: File does not exist: /user/hduser/terasort-output10-block-256/_partition.lst
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:624)
	at org.apache.hadoop.mapreduce.filecache.TaskDistributedCacheManager.setup(TaskDistributedCacheManager.java:166)
	at org.apache.hadoop.mapred.TaskRunner$1.run(TaskRunner.java:187)
	at org.apache.hadoop.mapred.TaskRunner$1.run(TaskRunner.java:182)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:742)
	at org.apache.hadoop.mapred.TaskRunner.run(TaskRunner.java:182)

2016-08-25 00:05:05,374 INFO org.apache.hadoop.mapred.JobTracker: Removing task 'attempt_201608242349_0001_r_000001_2'
2016-08-25 00:05:05,458 INFO org.apache.hadoop.mapred.JobTracker: Adding task (JOB_CLEANUP) 'attempt_201608242349_0001_m_000038_3' to tip task_201608242349_0001_m_000038, for tracker 'tracker_slave2:127.0.0.1/127.0.0.1:37601'
2016-08-25 00:05:08,461 INFO org.apache.hadoop.mapred.TaskInProgress: Error from attempt_201608242349_0001_m_000038_3 on tracker_slave2:127.0.0.1/127.0.0.1:37601: java.lang.Throwable: Child Error
	at org.apache.hadoop.mapred.TaskRunner.run(TaskRunner.java:249)
Caused by: java.io.FileNotFoundException: File does not exist: /user/hduser/terasort-output10-block-256/_partition.lst
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:624)
	at org.apache.hadoop.mapreduce.filecache.TaskDistributedCacheManager.setup(TaskDistributedCacheManager.java:166)
	at org.apache.hadoop.mapred.TaskRunner$1.run(TaskRunner.java:187)
	at org.apache.hadoop.mapred.TaskRunner$1.run(TaskRunner.java:182)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:742)
	at org.apache.hadoop.mapred.TaskRunner.run(TaskRunner.java:182)

2016-08-25 00:05:11,465 INFO org.apache.hadoop.mapred.TaskInProgress: TaskInProgress task_201608242349_0001_m_000038 has failed 4 times.
2016-08-25 00:05:11,466 INFO org.apache.hadoop.mapred.JobInProgress: Aborting job job_201608242349_0001
2016-08-25 00:05:11,467 INFO org.apache.hadoop.mapred.JobInProgress$JobSummary: jobId=job_201608242349_0001,submitTime=1472062821307,launchTime=1472062821576,finishTime=1472063711466,numMaps=38,numSlotsPerMap=1,numReduces=1,numSlotsPerReduce=1,user=hduser,queue=default,status=FAILED,mapSlotSeconds=24,reduceSlotsSeconds=18,clusterMapCapacity=8,clusterReduceCapacity=8
2016-08-25 00:05:11,569 INFO org.apache.hadoop.mapreduce.jobhistory.JobHistory: Moving file:/usr/local/hadoop/logs/history/job_201608242349_0001_hduser to file:/usr/local/hadoop/logs/history/done/job_201608242349_0001_hduser
2016-08-25 00:05:11,578 INFO org.apache.hadoop.mapred.JobTracker: Removing task 'attempt_201608242349_0001_m_000038_3'
2016-08-25 00:05:11,582 INFO org.apache.hadoop.mapreduce.jobhistory.JobHistory: Moving file:/usr/local/hadoop/logs/history/job_201608242349_0001_conf.xml to file:/usr/local/hadoop/logs/history/done/job_201608242349_0001_conf.xml
2016-08-25 00:05:11,589 INFO org.apache.hadoop.mapred.JobInProgress: Deleting localized job conf at /usr/local/hadoop/bin/../logs/job_201608242349_0001_conf.xml
2016-08-25 00:05:11,589 INFO org.apache.hadoop.mapred.JobTracker: Retired job with id: 'job_201608242349_0001' of user 'hduser'
